### ISSUE TITLE
Sugestão de criação de métrica de prioridade dos projeto e das funcionalidades.

### ISSUE THREAD

**Issue by joseiscj** [douglaslimaxx/proyecto#1]
Na tela inicial, onde há a listagem dos projetos, poderia haver a indicação de quão prioritário é a execução de cada projeto para o usuário. Funcionaria como uma espécie de indicação de importância, onde o usuário apontaria projetos que seriam mais importantes para serem realizados. Semelhantemente, na tela de exibição de detalhes de cada projeto, na listagem dos componentes, a indicação de quão prioritário é o desenvolvimento de cada componente poderia ser mostrado. O ícone de indicação de prioridade seria editável, já que um projeto ou componente pode se tornar mais importante em determinado momento do que já foi.

**Comment by douglaslimaxx** [comment]
Muito obrigado gostei da ideia @joseiscj . Mas tu acha que seria melhor adicionar um nota de prioridade, de 0 a 5, ou um label de importante, urgente ou normal.

**Comment by douglaslimaxx** [comment]
Ou até nos componentes de um projeto ter a opção de colocar em sequência de prioridade, tipo o primeiro da lista é o mais urgente e o último o menos.

**Comment by joseiscj** [comment]
Acredito que qualquer das duas formas ficaria legal.

**Comment by douglaslimaxx** [comment]
ok, muito obrigado
