### ISSUE TITLE
Adicionar 'key' aos componentes criados via mapeamento

### ISSUE THREAD

**Issue by alvesmatheus** [douglaslimaxx/proyecto#10]
Oi, @douglaslimaxx! Queria te dar uma sugestão sobre o uso do `Array.map()` pra criação de componentes... Quando se cria um componente para cada um dos objetos num array, o ideal é que cada um deles receba uma `key`. Essa `key` geralmente será um propriedade do próprio objeto gerador e atua como um identificador único.

O React (e outros *frameworks*, como o Vue) usam a `key` pra tornar o processo de atualizar a renderização mais eficiente. Com elas, quando um dos objetos da lista mudar, apenas o componente referente a esse objeto será renderizado novamente. Caso contrário, todos os componentes gerados precisarão ser renderizados (o que se torna lento à medida que a lista cresce).

Acho que a minha explicação não ficou tão clara, então vou deixar um exemplo usando teu código. Atualmente esse é um trecho do `Home.js`:

```js
<div id="container">
    {props.projects
        .filter((project) => project.name.toLowerCase().includes(search.toLowerCase()))
        .map((project) => (
            <a href="/create">
                <Project
                    img={project.img}
                    name={project.name}
                    description={project.description}
                    progress={project.progress}
                />
            </a>
    ))}
</div>
```
Considerando que cada um dos teus projetos tenha um nome único, você passaria a ter isso aqui:

```js
<div id="container">
    {props.projects
        .filter((project) => project.name.toLowerCase().includes(search.toLowerCase()))
        .map((project) => (
            <a key={project.name} href="/create"> // O componente é identificado pelo nome do projeto.
                <Project
                    img={project.img}
                    name={project.name}
                    description={project.description}
                    progress={project.progress}
                />
            </a>
        ))}
</div>
```

**Comment by douglaslimaxx** [comment]
Obrigado amigo, me livrei de alguns warnings com essa dica.
