### ISSUE TITLE
 Funcionalidades e GitHub Pages

### ISSUE THREAD

**Issue by juliobguedes** [douglaslimaxx/proyecto#2]
Oi Douglas,

Achei bem massa a ideia do projeto e provavelmente é algo que eu usaria (sabe aquela mesma lista do Studio Ghibli? me faltam 5 filmes até hoje...)

Acerca das funcionalidades, algo bem simples e que eu sugiro adicionar é adicionar um filtro de `Mostrar projetos concluídos?`. Outra coisa que seria legal era ter deadlines pras "tarefas" do projeto, mas acho que isso faz crescer bastante o escopo :/

Sobre o deploy no GitHub Pages, ainda não está funcionando, então não consigo ver o resultado do HTML da pasta frontend acessando https://douglaslimaxx.github.io/proyecto. Isso é algo relativamente simples de corrigir, nas configurações do repositório, ao "ativar" o GitHub Pages, só alterar a pasta da root pra frontend :)

**Comment by douglaslimaxx** [comment]
Gostei da ideia dos projetos concluídos, vou adicionar. E valeu pela dica do deploy, eu mudei a estrutura das pastas do projeto e não ajeitei o Github Pages.
