### ISSUE TITLE
Criar um service para gerenciar as requisições HTTP

### ISSUE THREAD

**Issue by jadsonluan** [douglaslimaxx/proyecto#9]
Oi, @douglaslimaxx ! 

Uma coisa que você pode fazer para encapsular a lógica de requisições HTTP é separar essas chamadas em um outro módulo (api.js, por exemplo) e nessa parte do código só fazer a chamada à algo como API.getProjects()

https://github.com/douglaslimaxx/proyecto/blob/534d007585b85093496b5d8616167b2fafed60ef/frontend/src/App.js#L14-L19

**Comment by douglaslimaxx** [comment]
Obrigado pela dica!
